name: Continuous Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test-and-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Setup
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Unit Test
        run: |
          npm run test